language: python
python:
  - "3.6"

matrix:
  include:
    - os: linux
      sudo: required
      dist: bionic
      compiler: gcc
      services:
        - docker

before_install:
  - export TZ=Asia/Dubai
  - date

script:
  - git remote add upstream https://github.com/sk1project/uniconvertor
  - git fetch upstream
  - git pull upstream master
  - sudo apt-get install -y sshpass gettext
  - mkdir subproj
  - git clone https://github.com/sk1project/build-utils subproj/build-utils
  - ln -s subproj/build-utils/src/utils utils
  - git clone https://github.com/sk1project/build-cache subproj/build-cache
  - python3 bbox.py pull
  - python3 bbox.py build
