language: python
python:
  - "2.7"

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      compiler: gcc
      services:
        - docker

script:
  - git remote add upstream https://github.com/sk1project/sk1-wx
  - git fetch upstream
  - git pull upstream master
  - sudo apt-get install -y sshpass gettext
  - mkdir subproj
  - git clone https://github.com/sk1project/build-utils subproj/build-utils
  - ln -s ./subproj/build-utils/src/utils utils
  - python bbox.py pull
  - python bbox.py build
